'use strict';
const $=s=>document.querySelector(s), canvas=$('#kitchen'),ctx=canvas.getContext('2d');
const C={ink:'#64463a',muted:'#a18972',pink:'#dd7383',green:'#8da875',cream:'#fff9ec',wood:'#dfb885'};
const recipes=[
 {id:'omelette',name:'暖心蛋包飯',en:'SUNSHINE OMELETTE',color:'#f7e8bd',desc:'將第一朝嘅陽光，包入軟綿綿嘅雞蛋。',story:'Sally 搬入新屋，廚房仲有幾個未拆嘅紙箱。窗邊嘅陽光照住一本空白食譜簿。「第一頁，就由一份暖笠笠嘅蛋包飯開始啦！」',steps:['chop','stir','pour','fry','decorate']},
 {id:'pancake',name:'雲朵班戟',en:'CLOUD NINE PANCAKES',color:'#f1dfd2',desc:'鬆軟班戟，加一點甜蜜嘅鼓勵。',story:'隔籬屋嘅小朋友送嚟一籃士多啤梨。Sally 決定整一碟班戟回禮。小小嘅廚房，第一次傳出朋友嘅笑聲。',steps:['stir','pour','fry','decorate']},
 {id:'curry',name:'家鄉咖喱飯',en:'A TASTE OF HOME',color:'#e4ebd4',desc:'慢慢煮嘅咖喱，總會令人掛住屋企。',story:'落雨嘅下午，Sally 打開屋企寄嚟嘅包裹：一張手寫咖喱食譜。「記得煮俾朋友食呀。」佢一邊切菜，一邊諗住熟悉嘅味道。',steps:['peel','chop','stir','fry','decorate']},
 {id:'pasta',name:'花園番茄意粉',en:'GARDEN TOMATO PASTA',color:'#eddfd3',desc:'番茄同香草，將小花園搬上餐桌。',story:'窗台嘅羅勒終於長大。Sally 約咗朋友一齊食晚飯，每個人帶一樣材料。原來最好嘅食譜，係大家一齊寫出嚟。',steps:['chop','pour','stir','fry','decorate']},
 {id:'fish',name:'香煎檸檬魚',en:'LEMON BUTTER FISH',color:'#dfeae2',desc:'金黃魚柳同清新檸檬，火候最重要。',story:'週末市集就快開始，Sally 想試吓擺檔。佢揀咗自己最怕煎燶嘅魚柳練習。「失手都唔緊要，再試一次。」',steps:['chop','pour','fry','decorate']},
 {id:'soup',name:'暖暖南瓜湯',en:'GOLDEN PUMPKIN SOUP',color:'#f1e2bf',desc:'用一碗濃湯，留住一個溫暖下午。',story:'市集嗰日突然轉涼。Sally 臨時煮咗一大煲南瓜湯。路過嘅人捧住熱湯傾偈，細細張枱變成咗最熱鬧嘅地方。',steps:['peel','chop','pour','stir','fry']},
 {id:'sushi',name:'彩虹飯糰',en:'LITTLE RAINBOW BITES',color:'#e7e3ed',desc:'將五彩食材，捲成一口一個嘅快樂。',story:'市集朋友提議一齊開間小店。Sally 用彩色飯糰畫低每個人嘅夢想。門牌寫乜好呢？大家一齊答：「Cooking Sally！」',steps:['chop','stir','shape','decorate']},
 {id:'cake',name:'開張士多啤梨蛋糕',en:'OUR LITTLE CELEBRATION',color:'#f3dce1',desc:'將所有心意，變成開張日最甜嘅一頁。',story:'開張前一晚，Sally 翻到食譜簿最後一頁。由第一份早餐，到今日滿屋朋友，原來佢已經行咗好遠。「最後一道菜，一齊完成啦！」',steps:['stir','pour','fry','shape','decorate']}
];
const stepDefs={
 chop:{name:'切一切！',instruction:'沿住虛線向下劃，切開食材。',tip:'由虛線上面向下劃，每刀切到底。',gesture:'↓ 沿虛線向下劃',time:28,target:6},
 peel:{name:'刨走外皮！',instruction:'喺薯仔上由上向下劃，刨乾淨外皮。',tip:'長長一劃先刨得乾淨，唔好只係點一下。',gesture:'↓ 按住食材向下刨',time:26,target:5},
 stir:{name:'拌勻啲材料！',instruction:'按住碗邊順時針畫圈，攪拌 4 圈。',tip:'沿住碗內虛線慢慢畫圈，太貼中心唔算。',gesture:'↻ 按住順時針畫圈',time:32,target:Math.PI*8},
 pour:{name:'份量啱啱好！',instruction:'按住水壺倒入材料，去到綠色線就放手。',tip:'綠色範圍係 65–80%，記得及時放手。',gesture:'按住水壺倒入 · 放手停止',time:18,target:1},
 fry:{name:'掌握火候！',instruction:'拖動火力掣，保持綠區；提示出現時點鑊翻面。',tip:'火力綠區會改變。跟住調節，夠鐘記得翻面。',gesture:'↔ 拖動火力 · 點鑊翻面',time:35,target:9},
 shape:{name:'整靚個形！',instruction:'將右邊材料拖到碟上嘅虛線位置。',tip:'按住材料，拖到同色虛線圈再放手。',gesture:'拖住材料 → 虛線圈',time:30,target:4},
 decorate:{name:'加上最後心意！',instruction:'將配料拖到碟上 4 個綠色位置。',tip:'最後一步，逐件配料放到指定位置。',gesture:'拖住配料 → 綠色圈',time:28,target:4}
};
let save={scores:{},music:false};try{const s=JSON.parse(localStorage.getItem('cooking-sally-v1'));if(s&&s.scores)save=s;}catch{}
let practice=false,selected=0,mode='menu',stepIndex=0,results=[],mini={},paused=false,clock=0,particles=[],drag=null,hold=false,lastPoint=null,feedbackUntil=0,manualClock=false,finalScore=0;
const music=new Audio('assets/kitchen-waltz.wav');music.loop=true;music.volume=.3;let audioCtx=null,master=null,analyser=null,musicSource=null,audioEnabled=false;
function audioInit(){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.38;analyser=audioCtx.createAnalyser();analyser.fftSize=1024;master.connect(analyser);analyser.connect(audioCtx.destination);musicSource=audioCtx.createMediaElementSource(music);musicSource.connect(master);}audioCtx.resume();}
function tone(freq=600,duration=.09,type='sine',volume=.2){if(!audioEnabled)return;audioInit();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(master);o.start();o.stop(audioCtx.currentTime+duration);}
function chime(good=true){[0,1,2].forEach((n)=>setTimeout(()=>tone((good?[523,659,784]:[392,330,262])[n],.23,'triangle',.3),n*100));}
async function setSound(on){audioEnabled=on;save.music=on;persist();$('#sound').textContent=on?'♫ 音樂：開':'♫ 音樂：關';if(on){audioInit();try{await music.play();}catch{toast('再按一次音樂按鈕開始播放。');}}else music.pause();}
function persist(){try{localStorage.setItem('cooking-sally-v1',JSON.stringify(save));}catch{}}
function toast(t){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),3000);}
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function modal(html,actions=[]){$('#modal-content').innerHTML=html;const box=document.createElement('div');box.className='modal-actions';actions.forEach(a=>{let b=document.createElement('button');b.textContent=a.label;b.className=a.primary?'primary':'plain';b.onclick=()=>{$('#modal').close();a.fn();};box.append(b);});$('#modal-content').append(box);if(!$('#modal').open)$('#modal').showModal();}
function medal(score){return score>=90?'🥇':score>=75?'🥈':score>=60?'🥉':'♡';}
function unlocked(i){return i===0||recipes.slice(0,i).every(r=>(save.scores[r.id]||0)>=60);}
function roundRect(g,x,y,w,h,r,color,stroke){g.beginPath();g.roundRect(x,y,w,h,r);g.fillStyle=color;g.fill();if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke();}}
function ellipse(g,x,y,rx,ry,color,rot=0){g.beginPath();g.ellipse(x,y,rx,ry,rot,0,Math.PI*2);g.fillStyle=color;g.fill();}
function line(g,x1,y1,x2,y2,color,width=3){g.strokeStyle=color;g.lineWidth=width;g.lineCap='round';g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.stroke();}
function text(g,t,x,y,size=18,color=C.ink,align='center'){g.fillStyle=color;g.font=`600 ${size}px -apple-system, "PingFang TC", sans-serif`;g.textAlign=align;g.textBaseline='middle';g.fillText(t,x,y);}
function leaf(g,x,y,size=12,angle=0){g.save();g.translate(x,y);g.rotate(angle);ellipse(g,0,0,size,size*.42,'#679754',-.55);line(g,-size*.7,size*.3,size*.6,-size*.25,'#a3bb73',1.5);g.restore();}
function berry(g,x,y,size=12){g.save();g.translate(x,y);g.beginPath();g.moveTo(-size,-size*.5);g.bezierCurveTo(-size*1.4,size*.2,-size*.25,size,0,size*1.3);g.bezierCurveTo(size*.5,size,size*1.3,0,size,-size*.5);g.bezierCurveTo(size*.5,-size,0,-size*.8,-size,-size*.5);g.fillStyle='#d95a5e';g.fill();for(let i=0;i<5;i++)ellipse(g,(i%2?-.35:.35)*size,(i*.27-.3)*size,1,1.5,'#ffd48c');leaf(g,0,-size*.6,size*.65,0);g.restore();}
function plate(g,x,y,rx=166,ry=116){ellipse(g,x,y+8,rx+7,ry+3,'#a9876030');ellipse(g,x,y,rx,ry,'#d1dcd4');ellipse(g,x,y-3,rx-4,ry-3,'#fffdf4');g.strokeStyle='#d1dcd4';g.lineWidth=2;g.beginPath();g.ellipse(x,y-3,rx-24,ry-19,0,0,Math.PI*2);g.stroke();}
function dish(g,id,x,y,scale=1,finished=true){if(FoodArt.sprite(g,'meals',recipes.findIndex(r=>r.id===id),x,y,365*scale,255*scale))return;g.save();g.translate(x,y);g.scale(scale,scale);plate(g,0,0);if(id==='omelette'){ellipse(g,0,6,110,60,'#d9942d');ellipse(g,-2,0,110,57,'#f8cd53');ellipse(g,-15,-16,78,25,'#ffe798');g.strokeStyle='#d7594c';g.lineWidth=10;g.lineCap='round';g.beginPath();g.moveTo(-65,2);g.bezierCurveTo(-35,-35,-35,35,0,0);g.bezierCurveTo(35,-35,35,35,68,0);g.stroke();leaf(g,110,-23,18,0);}else if(id==='pancake'){for(let i=2;i>=0;i--){ellipse(g,0,i*13-10,100,57,'#ac7036');ellipse(g,0,i*13-16,100,51,'#edbc6e');}ellipse(g,0,-25,78,34,'#c98a46');roundRect(g,-17,-44,34,22,5,'#ffe393');berry(g,-67,-26,18);berry(g,72,-3,17);leaf(g,56,-39,16,-.3);}else if(id==='curry'){ellipse(g,-45,0,72,65,'#eee9d7');for(let i=0;i<65;i++)ellipse(g,-95+(i*19%100),-40+(i*31%78),4,2,'#fffdf3',i);ellipse(g,47,10,80,62,'#b5763b');for(let i=0;i<11;i++)roundRect(g,1+i*19%98,-33+i*29%83,20,17,4,i%2?'#e79b53':'#dec079');leaf(g,-55,-41,14);}else if(id==='pasta'){ellipse(g,0,0,105,65,'#e5b565');for(let i=0;i<24;i++){g.strokeStyle=i%3?'#f3ce80':'#d39f4c';g.lineWidth=6;g.beginPath();g.ellipse((i*37%100)-50,(i*23%55)-25,40+i%4*8,15+i%4*5,i*.23,0,Math.PI*1.8);g.stroke();}ellipse(g,2,-8,64,39,'#d66845');for(let i=0;i<8;i++)ellipse(g,i*27%97-45,i*17%40-30,9,7,'#e7804e');leaf(g,0,-30,23);leaf(g,20,-24,17,.9);}else if(id==='fish'){ellipse(g,0,0,110,47,'#c39449',-.12);ellipse(g,-2,-6,106,42,'#eac284',-.12);for(let i=0;i<5;i++)line(g,-65+i*28,-25,-80+i*28,25,'#b3854b',4);ellipse(g,104,-23,29,27,'#f2d061');ellipse(g,104,-23,23,21,'#fff0a7');for(let i=0;i<8;i++){const a=i*Math.PI/4;line(g,104,-23,104+Math.cos(a)*22,-23+Math.sin(a)*20,'#f8d875',2);}leaf(g,-110,-39,22);leaf(g,-92,-51,17,.7);}else if(id==='soup'){ellipse(g,0,3,117,79,'#b8c5b4');ellipse(g,0,-3,118,75,'#fffdf3');ellipse(g,0,-6,103,63,'#e8a044');g.strokeStyle='#fff1cb';g.lineWidth=5;g.beginPath();for(let a=0;a<12;a+=.1){const r=a*4;if(a===0)g.moveTo(0,-6);else g.lineTo(Math.cos(a)*r,Math.sin(a)*r*.55-6);}g.stroke();leaf(g,4,-8,17);}else if(id==='sushi'){for(let i=0;i<6;i++){const a=i%3*65-65,b=Math.floor(i/3)*54-27;ellipse(g,a,b+7,27,25,'#3e5141');ellipse(g,a,b,27,23,'#fffcdf');ellipse(g,a,b,15,13,'#cf8060');roundRect(g,a-9,b-8,12,11,2,'#e5a34d');leaf(g,a+6,b+3,8);}}else{roundRect(g,-94,-10,188,63,7,'#ead3a1');roundRect(g,-94,-22,188,28,7,'#fff9e7');roundRect(g,-94,19,188,11,3,'#e99b9c');ellipse(g,0,-21,94,46,'#fff8eb');for(let i=0;i<5;i++)berry(g,-67+i*33,-26+(i%2)*15,16);for(let i=0;i<6;i++)ellipse(g,-80+i*32,-49,9,8,'#fffdf7');}g.restore();}
const dishThumbs={};
function refreshFoodThumbs(){recipes.forEach(r=>{const c=document.createElement('canvas');c.width=480;c.height=360;dish(c.getContext('2d'),r.id,240,180,1.25);dishThumbs[r.id]=c.toDataURL();});}
refreshFoodThumbs();FoodArt.ready.then(loaded=>{if(loaded){refreshFoodThumbs();if(mode==='menu')renderMenu();document.querySelectorAll('img[data-food]').forEach(i=>i.src=dishThumbs[i.dataset.food]);render();}});

function renderMenu(){const complete=recipes.filter(r=>(save.scores[r.id]||0)>=60).length;$('#collection').textContent=`${complete} / 8`;$('#practice-toggle').textContent=`自由練習：${practice?'開':'關'}`;$('#recipe-grid').innerHTML='';recipes.forEach((r,i)=>{const open=practice||unlocked(i),score=save.scores[r.id];let b=document.createElement('button');b.className=`recipe-card ${open?'':'locked'}`;b.setAttribute('aria-label',`${r.name}${open?'':'，尚未解鎖'}`);b.innerHTML=`<div class="dish-art" style="--card:${r.color}"><span class="card-num">0${i+1}</span><span class="card-medal">${score?medal(score):open?'♡':'♧'}</span><img data-food="${r.id}" src="${dishThumbs[r.id]}" alt="${r.name}"></div><div class="card-info"><h3>${r.name}</h3><small>${r.en}</small><div class="card-bottom"><span>${open?`${r.steps.length} 個步驟 · 約 3 分鐘`:'完成上一道食譜解鎖'}</span><span>${score?score+' 分':open?'開始 →':'未解鎖'}</span></div></div>`;b.onclick=()=>{if(open)chooseRecipe(i);else toast('先完成上一道食譜（60 分），或者開啟自由練習。');};$('#recipe-grid').append(b);});}
function showMenu(){document.body.classList.remove('in-game');$('#thumb-console').hidden=true;mode='menu';paused=false;hold=false;drag=null;$('#modal').close();$('#game').hidden=true;$('#menu').hidden=false;renderMenu();window.scrollTo({top:0});}
function chooseRecipe(i){selected=i;const r=recipes[i];modal(`<div class="center"><span class="eyebrow">CHAPTER ${Math.floor(i/2)+1} · RECIPE 0${i+1}</span><h2>${r.name}</h2><img data-food="${r.id}" src="${dishThumbs[r.id]}" width="230" alt="${r.name}"><p>${r.story}</p>${practice?'<span class="practice-badge">自由練習 · 不限時 · 不影響解鎖</span>':''}</div>`,[{label:'返食譜簿',fn:showMenu},{label:'一齊煮啦 →',primary:true,fn:startRecipe}]);}
function startRecipe(){document.body.classList.add('in-game');$('#thumb-console').hidden=false;if(save.music&&!audioEnabled)setSound(true);stepIndex=0;results=[];$('#menu').hidden=true;$('#game').hidden=false;$('#recipe-name').textContent=recipes[selected].name;$('#aside-name').textContent=recipes[selected].name;$('#aside-desc').textContent=recipes[selected].desc;$('#best-label').textContent=save.scores[recipes[selected].id]?`最佳紀錄：${save.scores[recipes[selected].id]} 分`:'第一道心意，等你創作。';window.scrollTo({top:0});setupStep();}
function def(){return stepDefs[recipes[selected].steps[stepIndex]];}function kind(){return recipes[selected].steps[stepIndex];}
function setupStep(){const d=def();mode='ready';paused=false;drag=null;hold=false;lastPoint=null;particles=[];mini={progress:0,time:d.time,elapsed:0,cuts:0,angle:0,fill:0,heat:30,temp:25,cooked:0,flipped:false,burn:0,items:[false,false,false,false],mistakes:0,flash:0,targetHeat:58};$('#step-count').textContent=`STEP ${stepIndex+1} / ${recipes[selected].steps.length}${practice?' · PRACTICE':''}`;$('#step-name').textContent=d.name;$('#instruction').textContent=kind()==='fry'&&simmering()?'拖動火力掣保持綠區；提示出現時點鍋攪拌。':d.instruction;$('#tip-text').textContent=d.tip;$('#gesture-label').textContent=d.gesture;$('#mood').textContent='♡';$('#feedback').textContent='準備好就開始啦！';$('#steps').innerHTML=recipes[selected].steps.map((k,i)=>`<li class="${i===stepIndex?'active':i<stepIndex?'done':''}">${stepDefs[k].name}${i<stepIndex?' ✓':''}</li>`).join('');updateHud();render();}
function beginStep(){if(mode!=='ready')return;mode='playing';audioInit();tone(660,.1);$('#feedback').textContent='你得㗎，Sally 陪住你！';}
function say(t,good=true){$('#feedback').textContent=t;$('#mood').textContent=good?'✦':'!';feedbackUntil=clock+2;}
function burst(x,y,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:Math.cos(i*2.4)*70,vy:Math.sin(i*2.4)*70-40,life:.7,color:i%2?'#eab75b':'#d9808a'});}
function progressHit(amount,x=310,y=210){mini.progress+=amount;mini.flash=.16;tone(420+mini.progress*27,.07,'triangle');burst(x,y,5);if(mini.progress>=def().target)finishStep();}
function finishStep(forced){if(mode!=='playing')return;hold=false;drag=null;let score;if(forced!==undefined)score=forced;else{const fraction=Math.min(1,mini.progress/def().target);score=Math.round(fraction*100-mini.mistakes*5-mini.burn*3);if(kind()==='fry')score=Math.round((mini.cooked/9)*100-mini.burn*5-(mini.flipped?0:20));}score=Math.max(0,Math.min(100,score));results.push(score);mode='stepResult';chime(score>=60);$('#feedback').textContent=score>=90?'好靚呀，做得非常好！':score>=60?'好嘢！繼續下一步。':'唔緊要，下一步再努力！';$('#mood').textContent=score>=60?'♥':'♡';render();modal(`<div class="center"><div class="medal-big">${medal(score)}</div><span class="eyebrow">${def().name}</span><h2>${score>=90?'煮得好出色！':score>=60?'做得好呀！':'再試就會進步！'}</h2><div class="result-number">${score}<small style="font-size:18px"> / 100</small></div><p>${score>=90?'每一份細心，都變成咗美味。':score>=60?'完成咗呢一步，繼續一齊煮啦。':'Sally 幫你執好材料，繼續完成呢道菜。'}</p></div>`,[{label:stepIndex===recipes[selected].steps.length-1?'上菜睇成績 →':'下一步 →',primary:true,fn:()=>{stepIndex++;if(stepIndex>=recipes[selected].steps.length)finishRecipe();else setupStep();}}]);}
function finishRecipe(){mode='recipeResult';finalScore=Math.round(results.reduce((a,b)=>a+b,0)/results.length);let old=save.scores[recipes[selected].id]||0;if(!practice){save.scores[recipes[selected].id]=Math.max(old,finalScore);persist();}const r=recipes[selected];let ending=selected===7&&finalScore>=60&&!practice;modal(`<div class="center"><span class="eyebrow">${practice?'PRACTICE COMPLETE':'MADE WITH LOVE'}</span><h2>${ending?'Cooking Sally 開張啦！':r.name+'，上菜！'}</h2><img data-food="${r.id}" src="${dishThumbs[r.id]}" width="240" alt="完成料理"><div class="result-number">${medal(finalScore)} ${finalScore}</div><p>${ending?'熟悉嘅香味、滿枱嘅笑聲，Sally 終於明白：小店最重要嘅，係一齊食飯嘅人。多謝你陪佢完成第一本食譜簿。':practice?'練習完成！可以隨時再煮一次。':finalScore>=60?selected<7?'新食譜解鎖！下一份心意等緊你。':'全套食譜完成，試吓每道菜攞金牌啦！':'平均 60 分就可以解鎖下一道。再試一次啦！'}</p><div class="summary-steps">${r.steps.map((s,i)=>`<span>${stepDefs[s].name}</span><b>${results[i]} 分</b>`).join('')}</div></div>`,[{label:'再煮一次',fn:startRecipe},{label:'返食譜簿 →',primary:true,fn:showMenu}]);}
function updateHud(){updateThumb();$('#timer').textContent=practice?'◷ ∞':`◷ ${Math.max(0,mini.time||0).toFixed(1)}`;$('#timer').classList.toggle('danger-time',mini.time<8&&!practice);let f=mode==='menu'?0:Math.min(1,(mini.progress||0)/(def()?.target||1));$('#progress-fill').style.width=`${f*100}%`;$('#step-score').textContent=Math.round(f*100)+'%';}
function stepUpdate(dt){clock+=dt;particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=110*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(paused||mode!=='playing')return;mini.elapsed+=dt;mini.flash=Math.max(0,mini.flash-dt);if(!practice)mini.time-=dt;if(kind()==='pour'&&hold){mini.fill+=dt*.235;mini.progress=Math.min(1,mini.fill/.72);if(mini.fill>=1){say('倒得太多啦！',false);finishStep(30);return;}}if(kind()==='fry'){mini.targetHeat=mini.cooked<3?58:mini.cooked<6?38:65;mini.temp+=(mini.heat-mini.temp)*Math.min(1,dt*1.5);const good=Math.abs(mini.temp-mini.targetHeat)<12;if(good){mini.cooked+=dt;mini.progress=mini.cooked;if(mini.cooked>=4&&!mini.flipped){mini.cooked=Math.min(mini.cooked,5.2);say(simmering()?'而家點一下鍋，攪勻醬汁！':'而家點一下鑊，翻另一面！');}}if(mini.temp>mini.targetHeat+23)mini.burn+=dt;if(mini.cooked>=9&&mini.flipped){mini.progress=9;finishStep();return;}}if(mini.time<=0&&!practice){finishStep();return;}updateHud();}
function bg(){ctx.clearRect(0,0,620,420);ctx.fillStyle='#f7edda';ctx.fillRect(0,0,620,420);for(let y=0;y<420;y+=35){line(ctx,0,y,620,y,'#d5c6a71c',1);}roundRect(ctx,16,16,588,388,20,'#fffbf0','#e4d4b8');}
function grad(g,x0,y0,x1,y1,stops){const q=g.createLinearGradient(x0,y0,x1,y1);stops.forEach(([p,c])=>q.addColorStop(p,c));return q;}
function foodSprite(sheet,i,x,y,w,h=w,angle=0,alpha=1){return FoodArt.sprite(ctx,sheet,i,x,y,w,h,angle,alpha);}
function kitchenShadow(x,y,rx,ry){ctx.save();ctx.filter='blur(7px)';ellipse(ctx,x,y,rx,ry,'#57320d35');ctx.restore();}
function board(){
 kitchenShadow(311,335,244,16);
 roundRect(ctx,48,69,524,281,24,'#94602f','#8c5d2b');
 roundRect(ctx,44,58,524,281,24,grad(ctx,0,58,0,340,[[0,'#efd49e'],[.35,'#eac486'],[.8,'#d6a465'],[1,'#c99657']]),'#bd864d');
 ctx.save();ctx.beginPath();ctx.roundRect(52,66,508,265,19);ctx.clip();
 for(let i=0;i<55;i++){const y=70+i*4.8;ctx.strokeStyle=i%5?'#9c682f12':'#98662d30';ctx.lineWidth=i%5?1:1.6;ctx.beginPath();for(let x=44;x<568;x+=12){const yy=y+Math.sin(x*.024+i*.7)*2.5;if(x===44)ctx.moveTo(x,yy);else ctx.lineTo(x,yy);}ctx.stroke();}
 for(let i=0;i<14;i++)line(ctx,100+i*31,145+(i*41)%160,141+i*28,120+(i*41)%160,'#fff1c42a',1);
 ctx.restore();ctx.strokeStyle='#ad763c66';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(59,73,494,248,14);ctx.stroke();ellipse(ctx,68,198,5,24,'#a3753e');
}
function knife(x,y){
 ctx.save();ctx.translate(x,y);ctx.rotate(-.12);ctx.shadowColor='#54301944';ctx.shadowBlur=6;ctx.shadowOffsetX=5;
 const steel=grad(ctx,-15,0,18,0,[[0,'#737f81'],[.15,'#dde7e5'],[.52,'#fffdf0'],[.64,'#a9b7b6'],[1,'#e8eeee']]);
 ctx.beginPath();ctx.moveTo(-8,-21);ctx.lineTo(20,-21);ctx.lineTo(20,84);ctx.quadraticCurveTo(-1,78,-13,49);ctx.closePath();ctx.fillStyle=steel;ctx.fill();ctx.strokeStyle='#6e7b7c';ctx.lineWidth=1.5;ctx.stroke();ctx.shadowBlur=0;line(ctx,17,-15,17,75,'#fff',1.5);
 roundRect(ctx,-8,-86,27,68,8,grad(ctx,-8,0,20,0,[[0,'#3c3936'],[.5,'#786452'],[1,'#352e28']]),'#40362b');ellipse(ctx,5,-70,3,3,'#a8a69c');ellipse(ctx,5,-36,3,3,'#a8a69c');ctx.restore();
}
function chopIngredient(){const id=recipes[selected].id;return id==='pasta'?{whole:2,slice:6,name:'新鮮番茄'}:id==='soup'?{whole:3,slice:3,name:'香甜南瓜'}:{whole:0,slice:4,name:'紅蘿蔔'};}
function drawChop(){
 board();const info=chopIngredient(),cut=mini.cuts,edge=112+cut*51;
 kitchenShadow(308,272,199,13);
 ctx.save();ctx.beginPath();ctx.rect(edge,96,560-edge,220);ctx.clip();foodSprite('ingredients',info.whole,310,204,424,245);ctx.restore();
 for(let i=0;i<cut;i++){const size=info.whole===0?66:78;foodSprite('ingredients',info.slice,128+i*51,250+(i%2)*10,size,info.whole===0?95:93,(i%3-1)*.14);}
 if(cut<6){const x=163+cut*51;ctx.setLineDash([7,6]);line(ctx,x,122,x,293,'#fffdeb',3);ctx.setLineDash([]);knife(x+16,117+Math.sin(Math.min(1,mini.flash/.16)*Math.PI)*75);text(ctx,'↓',x,301,26,'#b6573e');}
 roundRect(ctx,208,363,204,30,10,'#f0e0bd');text(ctx,`${info.name}  ·  ${Math.min(cut,6)} / 6 刀`,310,378,14,'#836139');
}
function drawPeel(){
 board();kitchenShadow(310,292,147,19);foodSprite('ingredients',5,309,197,330,282);
 ctx.save();ctx.beginPath();for(let i=mini.cuts;i<5;i++)ctx.rect(151+i*64,74,65,260);ctx.clip();foodSprite('ingredients',1,309,197,330,282);ctx.restore();
 for(let i=0;i<mini.cuts;i++){ctx.save();ctx.translate(463+(i%2)*27,202+i*25);ctx.rotate(i*.5);ctx.beginPath();ctx.moveTo(-8,-34);ctx.bezierCurveTo(23,-12,-19,10,9,34);ctx.strokeStyle='#9c6e3a';ctx.lineWidth=11;ctx.stroke();ctx.strokeStyle='#e3bd80';ctx.lineWidth=7;ctx.stroke();ctx.restore();}
 const px=mini.cuts<5?179+mini.cuts*64:420;ctx.save();ctx.translate(px,91);ctx.rotate(.15);roundRect(ctx,-12,-37,24,68,9,'#db786b','#9f5046');line(ctx,-32,26,32,26,'#848f8d',8);line(ctx,-29,24,29,24,'#eef3e9',3);ctx.restore();text(ctx,'↓',px,324,23,C.pink);text(ctx,`薄薄刨走外皮  ·  ${mini.cuts} / 5`,310,378,15,'#836139');
}
function enamelBowl(x=310,y=204){
 kitchenShadow(x,y+118,169,20);ellipse(ctx,x,y+15,176,143,grad(ctx,0,y-100,0,y+158,[[0,'#819694'],[.5,'#d4e3e2'],[1,'#779390']]));ellipse(ctx,x,y,179,137,'#faffee');ellipse(ctx,x,y-3,169,128,'#b8d3d0');ellipse(ctx,x,y-4,157,116,grad(ctx,0,y-120,0,y+110,[[0,'#7eaaa6'],[.35,'#f4f9ed'],[1,'#b9d3cb']]));ctx.strokeStyle='#f8ffef';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y-6,171,127,0,Math.PI,Math.PI*1.9);ctx.stroke();
}
function drawStir(){
 enamelBowl();const id=recipes[selected].id,f=Math.min(1,mini.progress/(Math.PI*8));
 ctx.save();ctx.beginPath();ctx.ellipse(310,197,149,109,0,0,Math.PI*2);ctx.clip();
 if(id==='curry'||id==='pasta'){foodSprite('cooking',id==='curry'?6:7,310,198,345,250);for(let i=0;i<8;i++){const a=i*.9+mini.angle;foodSprite('ingredients',i%2?4:5,310+Math.cos(a)*80,195+Math.sin(a)*52,35,26,a,1-f*.7);}}
 else if(id==='sushi'){foodSprite('details',0,310,198,330,240,Math.sin(mini.angle*.3)*.035);}
 else {foodSprite('cooking',id==='omelette'?0:2,310,198,349,260);if(id==='omelette'){foodSprite('details',7,310,198,260,184,mini.angle*.08,1-f);}else{foodSprite('details',6,310,198,220,140,mini.angle*.1,.8*(1-f));}}
 for(let j=0;j<4;j++){ctx.strokeStyle=['#fff2c05c','#b58a4138','#fffbe04a','#e6bc6744'][j];ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(310,198,40+j*26,22+j*17,Math.sin(mini.angle)*.06,mini.angle+j,mini.angle+j+2.5);ctx.stroke();}
 ctx.restore();ctx.setLineDash([3,9]);ctx.strokeStyle='#faffde99';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(310,198,100,80,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
 const x=310+Math.cos(mini.angle)*90,y=198+Math.sin(mini.angle)*66;ctx.save();ctx.translate(x,y);ctx.rotate(-.5);line(ctx,0,-12,0,-103,'#9b6232',15);line(ctx,-2,-23,-2,-99,'#d4a367',4);if(['sushi','curry','pasta'].includes(id)){ellipse(ctx,0,13,20,31,grad(ctx,-20,0,20,0,[[0,'#9d6434'],[.45,'#e3bc78'],[1,'#b57d43']]));line(ctx,-5,-8,-5,34,'#f3d797',2);}else for(let i=-2;i<=2;i++){ctx.strokeStyle=i%2?'#9ca9a4':'#d9e2d6';ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(0,13,9+Math.abs(i)*5,30,i*.15,0,Math.PI*2);ctx.stroke();}ctx.restore();
 text(ctx,`順時針拌勻  ·  ${Math.min(4,Math.floor(mini.progress/(Math.PI*2)))} / 4 圈`,310,378,15,C.muted);
}
function pourInfo(){const id=recipes[selected].id;return id==='omelette'?{name:'蛋液',color:'#f3bc29',light:'#ffe773'}:id==='fish'?{name:'橄欖油',color:'#b5a543',light:'#e7d879'}:id==='soup'?{name:'高湯',color:'#c89538',light:'#edd19c'}:id==='pasta'?{name:'清水',color:'#a8d5d6',light:'#e5f5ec'}:{name:'牛奶',color:'#e8ddbd',light:'#fffbed'};}
function drawPour(){
 const info=pourInfo();roundRect(ctx,56,330,514,22,8,grad(ctx,0,330,0,352,[[0,'#d8b17d'],[1,'#b68651']]));kitchenShadow(262,331,120,10);
 ctx.save();ctx.beginPath();ctx.moveTo(130,95);ctx.lineTo(354,95);ctx.lineTo(384,125);ctx.lineTo(353,141);ctx.lineTo(348,325);ctx.quadraticCurveTo(257,352,150,326);ctx.closePath();ctx.fillStyle=grad(ctx,120,0,360,0,[[0,'#88b4b544'],[.25,'#fafff199'],[.7,'#dbecda77'],[1,'#80a9a877']]);ctx.fill();ctx.strokeStyle='#96b8b2';ctx.lineWidth=3;ctx.stroke();ctx.clip();
 const ly=325-Math.min(1,mini.fill)*213;ctx.fillStyle=grad(ctx,0,ly,0,330,[[0,info.light],[1,info.color]]);ctx.fillRect(133,ly,224,220);ellipse(ctx,245,ly,112,12,info.light);for(let i=0;i<9;i++)ellipse(ctx,157+(i*29)%188,ly+8+(i%3)*8,2,1,'#fffbe877');ctx.restore();
 ctx.strokeStyle='#98b1aa';ctx.lineWidth=9;ctx.beginPath();ctx.roundRect(96,144,51,113,19);ctx.stroke();ctx.strokeStyle='#f7fff3';ctx.lineWidth=3;ctx.stroke();line(ctx,161,117,167,309,'#ffffffa0',5);
 for(let i=1;i<=5;i++){const y=323-i*37;line(ctx,291,y,332,y,'#788e80',2);text(ctx,''+(i*100),281,y,10,'#6e877b','right');}
 roundRect(ctx,145,154,207,31,2,'#7aba7455');line(ctx,142,170,360,170,'#69a064',3);text(ctx,'啱啱好',225,170,14,'#4a7446');
 ctx.save();ctx.translate(473,143);ctx.rotate(hold?-.6:0);kitchenShadow(0,92,50,8);roundRect(ctx,-47,-64,94,140,18,grad(ctx,-47,0,47,0,[[0,'#b8c5b6'],[.2,'#ffffef'],[.73,'#f1f2dc'],[1,'#a5b8ac']]),'#9aad9c');roundRect(ctx,-37,-20,74,61,5,info.color);text(ctx,info.name,0,10,15,'#68593f');roundRect(ctx,-36,-75,72,20,5,'#a6bfc0','#839e9a');roundRect(ctx,-32,-79,64,12,4,'#dcebe1');ctx.restore();
 if(hold){ctx.strokeStyle=info.light;ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(413,90);ctx.quadraticCurveTo(364,112,289,325-Math.min(.95,mini.fill)*213);ctx.stroke();ctx.strokeStyle='#fff9e877';ctx.lineWidth=3;ctx.stroke();}
 text(ctx,`${info.name}  ${Math.round(mini.fill*100)}%`,249,377,19,C.ink);text(ctx,'按住倒入',476,280,14,C.muted);
}
function simmering(){return ['curry','pasta','soup'].includes(recipes[selected].id);}
function stove(){
 roundRect(ctx,50,30,522,280,16,grad(ctx,0,30,0,310,[[0,'#e4e8e0'],[.25,'#f7f8eb'],[.9,'#c8d0c5'],[1,'#b0bdb0']]),'#b0b9ac');
 roundRect(ctx,64,42,493,252,9,'#edeedf','#ccd2c6');
 for(let i=0;i<4;i++)ellipse(ctx,77+i%2*467,56+Math.floor(i/2)*224,3,3,'#9aa899');
 ellipse(ctx,287,181,160,112,'#758076');ellipse(ctx,287,175,154,108,'#262e2b');
 if(mini.heat>5){for(let i=0;i<18;i++){const a=i*Math.PI*2/18;ellipse(ctx,287+Math.cos(a)*148,175+Math.sin(a)*103,4,8+Math.sin(clock*8+i)*3,'#4fbee3',-a);}}
}
function drawFry(){
 stove();const stew=simmering(),id=recipes[selected].id;
 kitchenShadow(293,275,171,16);
 if(stew){roundRect(ctx,78,139,80,40,10,'#8d5c3c','#573e2d');roundRect(ctx,416,139,79,40,10,'#8d5c3c','#573e2d');ellipse(ctx,287,183,166,118,grad(ctx,0,60,0,300,[[0,'#d49360'],[.4,'#a55d36'],[1,'#623e2f']]));}
 else {roundRect(ctx,421,151,156,33,15,grad(ctx,0,151,0,184,[[0,'#444944'],[.4,'#65685a'],[1,'#262d28']]),'#323d35');roundRect(ctx,546,161,17,10,5,'#c4c9b6');}
 ellipse(ctx,287,161,164,121,'#c5ccc0');ellipse(ctx,287,160,159,115,'#454d43');ellipse(ctx,287,157,149,106,grad(ctx,0,56,0,260,[[0,'#262e29'],[.6,'#414b3c'],[1,'#59634e']]));
 for(let i=0;i<110;i++){const a=i*2.4,r=Math.sqrt(i/110);ellipse(ctx,287+Math.cos(a)*142*r,158+Math.sin(a)*98*r,1,1,i%2?'#cbd4ac33':'#13241d44');}
 let f=Math.min(1,mini.cooked/9);if(!mini.flipped)f=Math.min(.48,f);
 ctx.save();ctx.beginPath();ctx.ellipse(287,156,145,103,0,0,Math.PI*2);ctx.clip();
 if(id==='curry'||id==='pasta')foodSprite('cooking',id==='curry'?6:7,287,156,330,250);
 else if(id==='soup'){foodSprite('details',3,287,156,330,250);for(let i=0;i<6;i++)foodSprite('ingredients',3,210+i%3*77,120+Math.floor(i/3)*65,66,54,i*.5,1-f);}
 else {const raw=id==='fish'?4:id==='omelette'?0:2,cooked=id==='fish'?5:id==='omelette'?1:3;const fw=id==='fish'?290:257,fh=id==='fish'?217:207;foodSprite('cooking',raw,287,158,fw,fh,0,1);foodSprite('cooking',cooked,287,158,fw,fh,0,f);}
 if(mini.burn>1){ctx.globalAlpha=Math.min(.6,mini.burn*.07);ellipse(ctx,287,158,110,80,'#56341d');ctx.globalAlpha=1;}
 ctx.restore();
 if(mini.heat>20){for(let i=0;i<14;i++){const a=i*.67+clock*.12,rx=stew?110:125,ry=stew?74:85;const x=287+Math.cos(a)*rx,y=157+Math.sin(a)*ry,r=1+(clock*3+i)%4;ctx.strokeStyle=stew?'#ffe6a579':'#ecd77b95';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();}}
 for(let i=0;i<4;i++){if(mini.cooked>.5||mini.temp>50){const y=90-((clock*24+i*23)%68);ctx.save();ctx.globalAlpha=.12+Math.sin(clock+i)*.04;ctx.strokeStyle='#fff9e9';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(228+i*35,108);ctx.bezierCurveTo(205+i*35,80,252+i*35,70,229+i*35,y);ctx.stroke();ctx.restore();}}
 if(mini.cooked>=4&&!mini.flipped){roundRect(ctx,197,136,181,45,14,'#fff9ebee');text(ctx,stew?'點我攪一攪 ↻':'點我翻面 ↻',287,159,17,C.pink);}
 text(ctx,stew?(mini.flipped?'已拌勻 ✓':'慢慢煮出香味'):mini.flipped?'另一面開始煎香 ✓':'由生到熟，留意顏色',291,288,12,C.muted);
 roundRect(ctx,85,338,450,19,9,'#d9c7b0');const tx=85+(mini.targetHeat-12)/100*450;roundRect(ctx,tx,338,108,19,9,'#99b67b');const hx=85+mini.heat/100*450;ellipse(ctx,hx,347,16,16,'#fff8ed');ellipse(ctx,hx,347,10,10,'#d4767f');text(ctx,'▼',85+mini.temp/100*450,325,15,'#b68a4c');text(ctx,'細火',85,382,12,C.muted);text(ctx,`保持綠區 · ${mini.cooked.toFixed(1)} / 9 秒`,310,388,14,C.ink);text(ctx,'大火',535,382,12,C.muted);
}
const slots=[{x:220,y:140},{x:360,y:140},{x:220,y:258},{x:360,y:258}];
function parsley(x,y,size=23,angle=0){if(foodSprite('details',1,x,y,size*2.3,size*2.3,angle))return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);for(let j=0;j<3;j++){const a=j*2.1;for(let i=0;i<7;i++){const b=i*.9,xx=Math.cos(a)*size*.4+Math.cos(b)*size*.32,yy=Math.sin(a)*size*.4+Math.sin(b)*size*.32;ellipse(ctx,xx,yy,size*.25,size*.2,i%2?'#478336':'#649b43',b);}line(ctx,0,0,Math.cos(a)*size*.85,Math.sin(a)*size*.85,'#a0b466',1);}ctx.restore();}
function sushiPiece(x,y){if(foodSprite('details',4,x,y,62,67))return;kitchenShadow(x,y+23,25,5);roundRect(ctx,x-25,y-3,50,35,10,grad(ctx,x-25,0,x+25,0,[[0,'#182c20'],[.5,'#43583a'],[1,'#1b3024']]),'#152219');ellipse(ctx,x,y,25,21,'#d7d8b8');for(let i=0;i<35;i++){const a=i*2.4,r=Math.sqrt(i/35);ellipse(ctx,x+Math.cos(a)*23*r,y+Math.sin(a)*18*r,3,1.4,i%3?'#fffdf0':'#eeeddb',a);}roundRect(ctx,x-10,y-10,15,16,3,'#eb8957');line(ctx,x-8,y-8,x+2,y+3,'#ffd3a3',1.5);roundRect(ctx,x+5,y-7,9,13,2,'#669547');}
function drawDrag(){const shaping=kind()==='shape';if(shaping){plate(ctx,284,202,190,152);}else dish(ctx,recipes[selected].id,283,203,1.12);roundRect(ctx,496,41,91,322,15,grad(ctx,496,0,586,0,[[0,'#c9bfa9'],[.15,'#f3efdb'],[.85,'#e7e2cd'],[1,'#b3b9a5']]),'#b5bea8');for(let i=0;i<4;i++){const p=slots[i];if(!mini.items[i]){ctx.setLineDash([5,5]);ctx.strokeStyle='#72945c';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(p.x,p.y,24,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);roundRect(ctx,p.x-9,p.y-9,18,18,5,'#fff9e2dd');text(ctx,''+(i+1),p.x,p.y,12,'#678554');}else drawPiece(p.x,p.y,i,shaping);if(!mini.items[i]&&drag?.index!==i)drawPiece(541,83+i*78,i,shaping);}if(drag)drawPiece(drag.x,drag.y,drag.index,shaping);text(ctx,`${mini.items.filter(Boolean).length} / 4 ${shaping?'份材料':'份配料'}`,280,382,15,C.muted);}
function drawPiece(x,y,i,shaping){if(shaping){if(recipes[selected].id==='cake'){foodSprite('details',5,x,y,64,68);foodSprite('ingredients',7,x,y-22,27,32);}else sushiPiece(x,y);}else if(['cake','pancake'].includes(recipes[selected].id))foodSprite('ingredients',7,x,y,49,58,(i%2-.5)*.2);else parsley(x,y,23,i*.4);}

function render(){if(mode==='menu')return;bg();const k=kind();if(k==='chop')drawChop();else if(k==='peel')drawPeel();else if(k==='stir')drawStir();else if(k==='pour')drawPour();else if(k==='fry')drawFry();else drawDrag();particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life*2);text(ctx,'✦',p.x,p.y,12,p.color);});ctx.globalAlpha=1;if(mode==='ready'){ctx.fillStyle='#fff9ecbb';ctx.fillRect(0,0,620,420);roundRect(ctx,93,108,434,201,22,'#fffdf4','#e5c9a5');text(ctx,def().name,310,150,29,C.ink);text(ctx,def().gesture,310,197,17,C.muted);roundRect(ctx,187,241,246,45,13,C.pink);text(ctx,'準備好，開始！',310,264,18,'#fff');}if(paused){ctx.fillStyle='#fff9ecbb';ctx.fillRect(0,0,620,420);text(ctx,'休息一下 ♡',310,210,30,C.ink);}}
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*620/r.width,y:(e.clientY-r.top)*420/r.height};}
function down(p){if(mode==='ready'){if(p.x>=93&&p.x<=527&&p.y>=108&&p.y<=309)beginStep();return;}if(mode!=='playing'||paused)return;lastPoint={...p,startX:p.x,startY:p.y,angle:Math.atan2(p.y-198,p.x-310)};if(kind()==='pour'){if(p.x>395&&p.y<265)hold=true;}if(kind()==='fry'){if(p.y>310){mini.heat=Math.max(0,Math.min(100,(p.x-85)/450*100));drag={type:'heat'};}else if(p.x>145&&p.x<440&&p.y>50&&p.y<280){if(mini.cooked>=4&&!mini.flipped){mini.flipped=true;tone(750,.18);burst(290,170);say(simmering()?'拌得好！繼續控制火候。':'靚靚翻面！繼續控制火候。');}else if(!mini.flipped){say('等第一面煎好先翻面。',false);}}}if(['shape','decorate'].includes(kind())){const i=Math.round((p.y-83)/78);if(p.x>493&&i>=0&&i<4&&!mini.items[i])drag={index:i,x:p.x,y:p.y};}}
function move(p){if(mode!=='playing'||paused||!lastPoint)return;const k=kind();if(k==='chop'||k==='peel'){const dy=p.y-lastPoint.startY,dx=Math.abs(p.x-lastPoint.startX),tx=k==='chop'?163+mini.cuts*51:310;const valid=k==='chop'?Math.abs(lastPoint.startX-tx)<30&&lastPoint.startY<180&&p.y>245:Math.abs(lastPoint.startX-tx)<110&&lastPoint.startY<160&&p.y>265;if(valid&&dy>90&&dx<75){mini.cuts++;lastPoint=null;say(k==='chop'?'切得好整齊！':'刨得好乾淨！');progressHit(1,p.x,p.y);return;}}else if(k==='stir'){const dx=p.x-310,dy=p.y-198,r=Math.hypot(dx,dy),a=Math.atan2(dy,dx);let delta=a-lastPoint.angle;while(delta>Math.PI)delta-=2*Math.PI;while(delta<-Math.PI)delta+=2*Math.PI;if(r>48&&r<160&&delta>0&&delta<.7){mini.angle+=delta;mini.progress+=delta;if(mini.progress>=def().target){finishStep();return;}}lastPoint.angle=a;}else if(drag?.type==='heat'){mini.heat=Math.max(0,Math.min(100,(p.x-85)/450*100));}else if(drag){drag.x=p.x;drag.y=p.y;}if(lastPoint){lastPoint.x=p.x;lastPoint.y=p.y;}}
function up(p){if(mode!=='playing'||paused){lastPoint=null;hold=false;drag=null;return;}if(kind()==='pour'&&hold){hold=false;const f=mini.fill;if(f<.1){say('按住耐少少，先有足夠材料。',false);}else{let score=f>=.65&&f<=.8?100:Math.max(10,Math.round(100-Math.abs(f-.725)*180));mini.progress=Math.min(1,f/.725);finishStep(score);}}if(drag&&drag.index!==undefined){const i=drag.index,t=slots[i];if(Math.hypot(p.x-t.x,p.y-t.y)<44){mini.items[i]=true;say('擺得好靚呀！');progressHit(1,t.x,t.y);}else{mini.mistakes++;say('拖去相同數字嘅綠圈，再放手。',false);tone(190,.1);}}drag=null;lastPoint=null;}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);down(point(e));render();});canvas.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType==='touch'){move(point(e));updateHud();render();}});canvas.addEventListener('pointerup',e=>{up(point(e));updateHud();render();});canvas.addEventListener('pointercancel',()=>{hold=false;drag=null;lastPoint=null;});
function pauseGame(){if(!['playing','ready'].includes(mode))return;paused=true;hold=false;drag=null;lastPoint=null;render();modal('<div class="center"><span class="eyebrow">A LITTLE TEA BREAK</span><h2>休息一下 ♡</h2><p>火爐熄低咗，時間亦停低咗。<br>準備好隨時返嚟繼續煮。</p></div>',[{label:'返食譜簿',fn:showMenu},{label:'繼續煮食 →',primary:true,fn:()=>{paused=false;render();}}]);}
$('#modal').addEventListener('cancel',e=>{e.preventDefault();if(paused){paused=false;$('#modal').close();render();}else if(mode==='menu')$('#modal').close();});
$('#start-btn').onclick=()=>chooseRecipe(Math.max(0,recipes.findIndex((r,i)=>unlocked(i)&&!(save.scores[r.id]>=60))));$('#practice-toggle').onclick=()=>{practice=!practice;renderMenu();};$('#story-btn').onclick=()=>modal('<div class="center"><span class="eyebrow">SALLY’S STORY</span><h2>一本空白嘅食譜簿。</h2><img class="modal-art" src="assets/sally.png" alt="Sally"><p>Sally 帶住一本空白食譜簿，搬入一間有陽光嘅小屋。由一份早餐、一籃士多啤梨，到市集上一碗熱湯，佢想用每道料理，認識一個新朋友。</p><p>完成 8 道菜，同佢一齊開一間<br>盛滿笑聲嘅小小餐廳。</p></div>',[{label:'打開食譜簿 →',primary:true,fn:()=>{}}]);
$('#sound').onclick=()=>setSound(!audioEnabled);$('#test-sound').onclick=async()=>{await setSound(true);await audioCtx.resume();chime();toast('試聲：三粒清脆音符 ♪');};$('#pause').onclick=pauseGame;$('#back').onclick=()=>{paused=true;hold=false;modal('<h2>返回食譜簿？</h2><p>今次未完成嘅料理進度唔會儲存，之前獲得嘅獎牌會保留。</p>',[{label:'繼續煮',fn:()=>{paused=false;}},{label:'返回食譜簿',primary:true,fn:showMenu}]);};$('#home-brand').onclick=e=>{e.preventDefault();if(mode==='menu')showMenu();else $('#back').click();};$('#help').onclick=()=>{const wasPaused=paused;paused=mode!=='menu';hold=false;drag=null;modal('<span class="eyebrow">HOW TO COOK</span><h2>用手指，煮出心意。</h2><div class="help-list"><b>iPhone 右手模式：</b>操作區固定喺右下角。向下劃切菜／刨皮、畫圈攪拌、按住倒材料、左右拖調火、點一下翻面、由右向左拖擺盤。<br><br><b>直接操作工作枱：</b><br>↓ 切菜 / 刨皮：按住食材，由上向下劃。<br>↻ 攪拌：沿碗邊順時針畫圈。<br>◡ 倒材料：按住水壺，綠線位置放手。<br>♨ 煎煮：拖火力掣跟綠區；提示出現時點鑊翻面。<br>✦ 塑形 / 擺盤：由右邊拖材料到對應數字。<br><br>每步最高 100 分。平均 60 分解鎖下一道；<br>90 分金牌、75 分銀牌、60 分銅牌。<br>自由練習不限時，可試全部食譜。<br>鍵盤：Enter 開始、P 暫停、F 全螢幕。</div>',[{label:'知道啦！',primary:true,fn:()=>{paused=wasPaused;}}]);};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();};document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='f')$('#fullscreen').click();if(e.key.toLowerCase()==='p'&&!$('#modal').open)pauseGame();if(e.key==='Enter'&&mode==='ready'&&!$('#modal').open)beginStep();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing'&&!paused)pauseGame();});
window.render_game_to_text=()=>JSON.stringify({mode,paused,practice,recipe:recipes[selected].id,step:stepIndex,kind:stepIndex<recipes[selected].steps.length?kind():null,coordinates:'canvas 620 x 420; origin top left; x right, y down',mini,results,finalScore,art:{ready:FoodArt.status.ready,failed:FoodArt.status.failed},unlocked:recipes.filter((r,i)=>unlocked(i)).map(r=>r.id),audio:{enabled:audioEnabled,musicPlaying:!music.paused,context:audioCtx?.state||'not-started'},targets:{chopX:163+(mini.cuts||0)*51,chopSwipe:[120,285],stir:{x:310,y:198,radius:100},pourHold:{x:470,y:150},heatSlider:{x:85,y:347,width:450},slots,tray:[0,1,2,3].map(i=>({x:541,y:83+i*78}))}});
window.advanceTime=ms=>{manualClock=true;for(let t=0;t<ms;t+=16.667)stepUpdate(Math.min(16.667,ms-t)/1000);updateHud();render();};
window.audio_probe=()=>{if(!analyser)return {rms:0};const a=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(a);return {rms:Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length),state:audioCtx.state,musicPlaying:!music.paused};};
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!manualClock)stepUpdate(dt);if(mode!=='menu'){updateHud();render();}requestAnimationFrame(loop);}renderMenu();requestAnimationFrame(loop);

let thumbGesture=null,activeThumbPointer=null;
function updateThumb(){if(mode==='menu')return;const k=stepIndex<recipes[selected].steps.length?kind():null;const info={chop:['↓','向下劃一刀','由上向下劃，逐刀切好'],peel:['↓','向下刨皮','按住向下劃，刨走外皮'],stir:['↻','順時針畫圈','喺操作區畫圈，拌勻材料'],pour:['◡','按住倒入 · 放手停','留意上面綠線，啱位就放手'],fry:['↔','左右拖調火力','跟住綠區調火；點一下翻面'],shape:['←','由右向左拖','逐份材料拖入碟中'],decorate:['←','由右向左拖','將每份配料放到碟上']};if(k==='fry'&&simmering())info.fry=['↔','左右拖調火力','跟住綠區調火；點一下攪拌'];const v=mode==='ready'?['▷','按一下開始','右手拇指放喺操作區']:info[k]||['♡','煮得好呀！','按下面按鈕繼續'];$('#thumb-symbol').textContent=v[0];$('#thumb-label').textContent=v[1];$('#thumb-hint').textContent=v[2];}
function thumbPoint(e){const r=$('#thumb-pad').getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};}
$('#thumb-pad').addEventListener('pointerdown',e=>{if(activeThumbPointer!==null)return;activeThumbPointer=e.pointerId;e.preventDefault();$('#thumb-pad').setPointerCapture(e.pointerId);if(mode==='ready'){beginStep();return;}if(mode!=='playing'||paused)return;const p=thumbPoint(e),k=kind();thumbGesture={start:p,last:p,moved:false,index:mini.items.findIndex(v=>!v)};if(k==='chop')down({x:163+mini.cuts*51,y:110});if(k==='peel')down({x:310,y:110});if(k==='stir')down({x:310+(p.x-.5)*240,y:198+(p.y-.5)*220});if(k==='pour')down({x:470,y:150});if(k==='fry')thumbGesture.initialHeat=mini.heat;if(k==='shape'||k==='decorate'){const i=thumbGesture.index;if(i>=0)down({x:541,y:83+i*78});}});
$('#thumb-pad').addEventListener('pointermove',e=>{if(e.pointerId!==activeThumbPointer)return;if(!thumbGesture||mode!=='playing'||paused)return;const p=thumbPoint(e),k=kind(),t=thumbGesture;t.moved=t.moved||Math.hypot(p.x-t.start.x,p.y-t.start.y)>.07;if(k==='chop'||k==='peel'){const dy=(p.y-t.start.y)*310;move({x:k==='chop'?163+mini.cuts*51:310,y:110+dy});}if(k==='stir')move({x:310+(p.x-.5)*240,y:198+(p.y-.5)*220});if(k==='fry'&&t.moved){mini.heat=Math.max(0,Math.min(100,t.initialHeat+(p.x-t.start.x)*130));}if((k==='shape'||k==='decorate')&&t.index>=0){const f=Math.min(1,Math.max(0,(t.start.x-p.x)/.55)),s=slots[t.index];move({x:541+(s.x-541)*f,y:83+t.index*78+(s.y-83-t.index*78)*f});}t.last=p;updateHud();render();});
$('#thumb-pad').addEventListener('pointerup',e=>{if(e.pointerId!==activeThumbPointer)return;activeThumbPointer=null;if(!thumbGesture)return;const t=thumbGesture,p=thumbPoint(e);if(mode==='playing'&&!paused){const k=kind();if(k==='fry'&&!t.moved)down({x:290,y:160});if((k==='shape'||k==='decorate')&&t.index>=0){const ok=t.start.x-p.x>.45;up(ok?slots[t.index]:{x:541,y:83+t.index*78});}else up({x:470,y:150});}thumbGesture=null;updateHud();render();});
$('#thumb-pad').addEventListener('pointercancel',()=>{activeThumbPointer=null;thumbGesture=null;hold=false;drag=null;lastPoint=null;});
$('#thumb-pad').addEventListener('keydown',e=>{if(e.key==='Enter'&&mode==='ready')beginStep();});
